# Generated by Django 5.1.4 on 2024-12-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_blogitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='blogText',
            field=models.TextField(),
        ),
    ]
