# Generated by Django 5.1.4 on 2025-07-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='note_photos/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='background_color',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
