# Generated by Django 5.1.4 on 2025-07-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_note_photo_alter_note_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='photo',
        ),
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_photos/'),
        ),
    ]
