# Generated by Django 5.1.4 on 2025-07-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_note_photo_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
