# Generated by Django 5.1.4 on 2025-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_note_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cathegory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
