# Generated by Django 5.1.4 on 2025-07-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_note_cathegory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='cathegory',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
    ]
